language: java
jdk: oraclejdk8
cache:
  directories:
    - closure-library
    - closure-compiler
    - closure-linter
    - python-gflags
notifications:
  email: false
before_install:
  - nvm install node
install:
  - npm ci
  - bash ./scripts/build-dependencies.sh
  - git clone --branch v`cat package.json | python -c "import sys, json; print(json.load(sys.stdin)['googleLibphonenumberVersion'])"` https://github.com/googlei18n/libphonenumber/
script:
  - bash ./scripts/execute.sh
  - npm test
before_deploy: echo "$(tput bold)$(tput setaf 6)Starting NPM release for version - `cat package.json | python -c "import sys, json; print(json.load(sys.stdin)['version'])"`"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: release
    condition: $TRAVIS_BRANCH = release
after_deploy: echo "$(tput bold)$(tput setaf 6)Completed Deployment of NPM version - `cat package.json | python -c "import sys, json; print(json.load(sys.stdin)['version'])"`"
